namespace Proyecto_BDII {
    public partial class PantallaADMIN {
        protected global::System.Web.UI.WebControls.Button btnLogout;
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.GridView GridView1;
        protected global::System.Web.UI.WebControls.TextBox TxtMarca;
        protected global::System.Web.UI.WebControls.TextBox TxtModelo;
        protected global::System.Web.UI.WebControls.TextBox TxtIMEI;
        protected global::System.Web.UI.WebControls.TextBox TxtAlmac;
        protected global::System.Web.UI.WebControls.TextBox TxtRAM;
        protected global::System.Web.UI.WebControls.TextBox TxtAno;
        protected global::System.Web.UI.WebControls.TextBox TxtSO;
        protected global::System.Web.UI.WebControls.TextBox TxtBanda;
        protected global::System.Web.UI.WebControls.TextBox TxtDescripcion;
        protected global::System.Web.UI.WebControls.DropDownList DdlCategoria;
        protected global::System.Web.UI.WebControls.DropDownList DdlProveedor;
        protected global::System.Web.UI.WebControls.TextBox TxtPrecio;
        protected global::System.Web.UI.WebControls.TextBox TxtStock;
        protected global::System.Web.UI.WebControls.FileUpload FuImagen;
        protected global::System.Web.UI.WebControls.Button BtnCrearCel;
        protected global::System.Web.UI.WebControls.GridView GridView2;
        protected global::System.Web.UI.WebControls.TextBox TxtCatNombre;
        protected global::System.Web.UI.WebControls.TextBox TxtCatDescripcion;
        protected global::System.Web.UI.WebControls.TextBox TxtCatIcono;
        protected global::System.Web.UI.WebControls.Button BtnCrearCateg;
        protected global::System.Web.UI.WebControls.GridView GridView4;
        protected global::System.Web.UI.WebControls.TextBox TxtProvEmpresa;
        protected global::System.Web.UI.WebControls.TextBox TxtProvNIT;
        protected global::System.Web.UI.WebControls.TextBox TxtProvContacto;
        protected global::System.Web.UI.WebControls.TextBox TxtProvTel;
        protected global::System.Web.UI.WebControls.TextBox TxtProvCorreo;
        protected global::System.Web.UI.WebControls.TextBox TxtProvDir;
        protected global::System.Web.UI.WebControls.Button BtnCrearProv;
        protected global::System.Web.UI.WebControls.DropDownList DdlCelularMov;
        protected global::System.Web.UI.WebControls.DropDownList DdlTipoMov;
        protected global::System.Web.UI.WebControls.TextBox TxtMovCantidad;
        protected global::System.Web.UI.WebControls.TextBox TxtMovMotivo;
        protected global::System.Web.UI.WebControls.Button BtnRegistrarMov;
        protected global::System.Web.UI.WebControls.GridView GridView5;
        protected global::System.Web.UI.WebControls.TextBox TxtBuscarUsuario;
        protected global::System.Web.UI.WebControls.TextBox TxtFechaDesde;
        protected global::System.Web.UI.WebControls.TextBox TxtFechaHasta;
        protected global::System.Web.UI.WebControls.Button BtnOrdenAsc;
        protected global::System.Web.UI.WebControls.Button BtnOrdenDesc;
        protected global::System.Web.UI.WebControls.Button BtnFiltrarVentas;
        protected global::System.Web.UI.WebControls.Button BtnLimpiarFiltros;
        protected global::System.Web.UI.WebControls.GridView GridView3;
    }
}
